### ISSUE TITLE
Problem with the C++ wrapper

### ISSUE THREAD

**Issue by mauriciosotogomez** [galanisl/NetHypGeom#1]
When I launch the code in the example I get an error related to the  hypermap function
 
`hm <- labne_hm(net = net$network, gma = 2.3, Temp = 0.15, k.speedup = 10, w = 2*pi)`
` Error in hypermap(as_data_frame(params$net, what = "edges"), params$gma,  :    object 'NetHypGeom_hypermap' not found`

**Comment by galanisl** [comment]
This was most likely because I left C++ binary files in the src folder, preventing the compilation of HyperMap code in the user's computer. The latest commit should solve this issue. Let me know!
