### ISSUE TITLE
[Installing Failure]Compilation failed

### ISSUE THREAD

**Issue by RiptideBo** [galanisl/NetHypGeom#2]
after I install Rtools, I use command - install_github("galanisl/NetHypGeom") - trying to install it.
But in then end, I encounter a problem. 
'''
ERROR: compilation failed for package 'NetHypGeom'
'''
How could I fix it? Could you please help me with it?

**Comment by galanisl** [comment]
Did you install library `devtools`? Are you installing this on Windows? Could you please share you `sessionInfo()`?

**Comment by galanisl** [comment]
Closed due to lack of feedback from @RiptideBo 
My tests of Ubuntu 16.04 LTS and macOS Sierra and High Sierra do not present installation problems.
